'use client';
import {useState} from 'react';
import {cleanSearch,downloadText,profileId,readPrivate,writePrivate,safeTracking} from '@/lib/private-profile';
const keys=['jobradar-search-preferences-v1','jobradar-tracking-v2','jobradar-resume-v1','jobradar-onboarded-v1'];
export function ProfilePanel(){
 const [message,setMessage]=useState(''),[link,setLink]=useState('');
 const create=()=>{const u=new URL(location.href);u.search='';u.searchParams.set('profile',crypto.randomUUID());u.hash='dashboard';location.assign(u.toString())};
 const share=()=>{const u=new URL(location.origin+location.pathname);u.searchParams.set('profile',crypto.randomUUID());let prefs={};try{prefs=JSON.parse(readPrivate(keys[0])||'{}')}catch{}u.searchParams.set('search',JSON.stringify(cleanSearch(prefs)));u.hash='all-jobs';setLink(u.toString());setMessage('This link includes search choices only. Notes, resume and applications are never included.')};
 const backup=()=>{const data:Record<string,unknown>={};for(const key of keys){try{data[key]=JSON.parse(readPrivate(key)||'null')}catch{}}downloadText('jobradar-private-backup.json',JSON.stringify({version:1,data},null,2),'application/json');setMessage('Backup contains private data. Store it somewhere you trust.')};
 const restore=async(file?:File)=>{if(!file)return;try{if(file.size>5_000_000)throw Error('Backup is larger than 5 MB.');const b=JSON.parse(await file.text());if(b.version!==1||!b.data||typeof b.data!=='object')throw Error('Choose a JobRadar version 1 backup.');if(!confirm('Replace preferences, resume and tracking in this profile with the backup?'))return;writePrivate(keys[0],JSON.stringify(cleanSearch(b.data[keys[0]])));writePrivate(keys[1],JSON.stringify(safeTracking(b.data[keys[1]])));const resume=b.data[keys[2]];if(resume&&typeof resume==='object')writePrivate(keys[2],JSON.stringify(resume));location.reload()}catch(e){setMessage(e instanceof Error?e.message:'Could not restore backup.')}};
 return <section className="mb-5 rounded-2xl border bg-white p-6 space-y-4"><h2 className="text-xl font-black">Your private workspace</h2><p className="text-sm text-slate-600">Profile: {profileId()}. Preferences, notes, resume and applications stay in this browser. A profile URL is a workspace label, not a login or a security boundary on a shared device. Use separate browser accounts for privacy. Export a backup before clearing browser data.</p><div className="flex flex-wrap gap-3"><a className="rounded-xl border px-4 py-2" href="/">Default profile</a><button className="rounded-xl bg-emerald-800 px-4 py-2 text-white" onClick={create}>Create separate profile</button><button className="rounded-xl border px-4 py-2" onClick={share}>Share search choices</button><button className="rounded-xl border px-4 py-2" onClick={backup}>Download private backup</button><label className="rounded-xl border px-4 py-2 cursor-pointer">Restore backup<input className="sr-only" type="file" accept="application/json,.json" onChange={e=>void restore(e.target.files?.[0])}/></label></div>{link&&<label className="block text-sm">Copy this search link<input readOnly value={link} onFocus={e=>e.target.select()} className="mt-2 w-full rounded-lg border p-3"/></label>}<p role="status" className="text-sm text-emerald-800">{message}</p><p className="text-xs text-slate-500">Everyone browses the same collected engineering jobs in Bengaluru and Hyderabad. Personal choices do not change the owner's scraper or Telegram alerts. No paid API or account is required for these tools.</p></section>
}
