'use client';
import {useState} from 'react';
import Link from 'next/link';
import {cleanSearch,downloadText,profileId,readPrivate,writePrivate,safeTracking} from '@/lib/private-profile';
const keys=['jobradar-search-preferences-v1','jobradar-tracking-v2','jobradar-resume-v1','jobradar-resume-draft-v1','jobradar-tailor-request-v1','jobradar-onboarded-v1'];
export function ProfilePanel(){
 const [message,setMessage]=useState(''),[link,setLink]=useState('');
 const create=()=>{const u=new URL(location.href);u.search='';u.searchParams.set('profile',crypto.randomUUID());u.hash='dashboard';location.assign(u.toString())};
 const share=()=>{const u=new URL(location.origin+location.pathname);u.searchParams.set('newWorkspace','1');let prefs={};try{prefs=JSON.parse(readPrivate(keys[0])||'{}')}catch{}u.searchParams.set('search',JSON.stringify(cleanSearch(prefs)));u.hash='all-jobs';setLink(u.toString());setMessage('This invite includes search choices only. Every person who opens it receives a new private workspace; notes, resume and applications are never included.')};
 const backup=()=>{const data:Record<string,unknown>={};for(const key of keys){try{data[key]=JSON.parse(readPrivate(key)||'null')}catch{}}downloadText('jobradar-private-backup.json',JSON.stringify({version:1,data},null,2),'application/json');setMessage('Backup contains private data. Store it somewhere you trust.')};
 const restore=async(file?:File)=>{if(!file)return;try{if(file.size>5_000_000)throw Error('Backup is larger than 5 MB.');const b=JSON.parse(await file.text());if(b.version!==1||!b.data||typeof b.data!=='object')throw Error('Choose a JobRadar version 1 backup.');if(!confirm('Replace preferences, resume and tracking in this profile with the backup?'))return;writePrivate(keys[0],JSON.stringify(cleanSearch(b.data[keys[0]])));writePrivate(keys[1],JSON.stringify(safeTracking(b.data[keys[1]])));const resume=b.data[keys[2]];if(resume&&typeof resume==='object')writePrivate(keys[2],JSON.stringify(resume));location.reload()}catch(e){setMessage(e instanceof Error?e.message:'Could not restore backup.')}};
 return <section className="mb-5 space-y-5 rounded-3xl border bg-white p-6"><div><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-800">Personal workspace</p><h2 className="mt-1 text-xl font-black">Use JobRadar without affecting anyone else</h2><p className="mt-2 text-sm leading-6 text-slate-600">Your searches, saved jobs, resume and application progress stay only in this browser workspace. Everyone shares the read-only company catalog, but personal progress never changes another person&apos;s data.</p></div><div className="grid gap-3 md:grid-cols-3"><div className="rounded-2xl bg-emerald-50 p-4"><b>1 · Create</b><p className="mt-1 text-xs leading-5 text-slate-600">Start a randomly named workspace for this browser.</p></div><div className="rounded-2xl bg-emerald-50 p-4"><b>2 · Personalize</b><p className="mt-1 text-xs leading-5 text-slate-600">Choose titles, skills, experience and city filters.</p></div><div className="rounded-2xl bg-emerald-50 p-4"><b>3 · Back up</b><p className="mt-1 text-xs leading-5 text-slate-600">Download a private file before clearing browser data.</p></div></div><p className="text-xs text-slate-500">Workspace: {profileId()}. This is local separation, not an account or login. Use a separate browser account on a shared computer for stronger privacy.</p><div className="flex flex-wrap gap-3"><Link className="rounded-xl border px-4 py-2" href="/">This browser&apos;s original workspace</Link><button className="rounded-xl bg-emerald-800 px-4 py-2 text-white" onClick={create}>Create my workspace</button><button className="rounded-xl border px-4 py-2" onClick={share}>Create search invite</button><button className="rounded-xl border px-4 py-2" onClick={backup}>Download private backup</button><label className="cursor-pointer rounded-xl border px-4 py-2">Restore backup<input className="sr-only" type="file" accept="application/json,.json" onChange={e=>void restore(e.target.files?.[0])}/></label></div>{link&&<label className="block text-sm font-bold">Copy this private-workspace invite<input readOnly value={link} onFocus={e=>e.target.select()} className="mt-2 w-full rounded-lg border p-3 font-normal"/></label>}<p role="status" className="text-sm text-emerald-800">{message}</p><p className="text-xs text-slate-500">No paid API or account is required. A recipient can change their own requirements without changing your searches, applications, resume or alerts.</p></section>
}
